// Code generated by @furo/ui-builder. DO NOT EDIT.


import "@furo/data-input";
import "@furo/form";
import "@furo/util/furo-keydown.js";

/**
 * Einfaches Anmeldeformular.
 *
 * @summary summary
 * @customElement
 * @polymer
 * @appliesMixin FBP
 */
export class LoginForm extends FBP(LitElement) {

  

  //Setze den Fokus
  focus(d) {
    this._FBPTriggerWire('--focused', d)
  }
  

  /**
   * flow is ready lifecycle method
   */
  _FBPReady() {
    super._FBPReady();
    //this._FBPTraceWires()
  }



  /**
   * Themable Styles
   * @private
   * @return {CSSResult}
   */
  static get styles() {
    // language=CSS
    return Theme.getThemeForComponent(this.component_name) || css`
      
      :host {
        display: block;
      }

      :host([hidden]) {
        display: none;
      }

    `
  }


  /**
   * @private
   * @returns {TemplateResult}
   * @private
   */
  render() {
    // language=HTML
    return html`

      <!-- Anmeldemaske mit auto-zentrierung -->
      <furo-form label="Anmeldumg" style="width:300px;margin:100px auto; border-top:5px solid #FEA248;">
        <furo-text-input label="Username" value="${this.username}" ƒ-focus="--ButtonClicked"></furo-text-input> 

        <!-- Könnten wir noch einen zeige kennwort implementieren? Falls es nicht zu schwierig ist... -->
        <furo-password-input label="Passowort" value="${this.password}"></furo-password-input> 

        <!-- Bin mir nicht sicher ob es den überhaupt braucht -->
        <furo-horizontal-flex>
          <furo-button label="Login" @-click="--ButtonClicked"></furo-button> 
        </furo-horizontal-flex> 
      </furo-form> 

      
    
      <furo-keydown ctrl key="x" @-key="--shortcutLPressed"></furo-keydown>
    
    `;
  }
}

window.customElements.define('login-form', LoginForm);

